version: "3.8"

services:
  discovery-service:
    image: rahulranjan26/linkedin-app-discovery-service:latest
    container_name: discovery-service
    ports:
      - "8761:8761"
    environment:
      - EUREKA_CLIENT_SERVICEURL_DEFAULTZONE=http://discovery-service:8761/eureka
    networks:
      - app-network

  zipkin:
    image: openzipkin/zipkin:latest
    container_name: zipkin
    ports:
      - "9411:9411"
    environment:
      - STORAGE_TYPE=mem
    networks:
      - app-network
    healthcheck:
      test: ["CMD", "wget", "--no-verbose", "--tries=1", "--spider", "http://localhost:9411/health"]
      interval: 30s
      timeout: 10s
      retries: 3

  api-gateway:
    image: rahulranjan26/linkedin-app-api-gateway:latest
    container_name: api-gateway
    depends_on:
      - discovery-service
      - zipkin
    ports:
      - "8080:8080"
    environment:
      - EUREKA_CLIENT_SERVICEURL_DEFAULTZONE=http://discovery-service:8761/eureka
      - SPRING_SECRET_KEY=dskjjnkfasndifuqhwkndsljfqadskmnadsjfiqjfkanKJkskanskniasmvjabasnanvksdnksaknkbajhvbvasbvakbvakslaabs
      - ZIPKIN_URL=http://zipkin:9411
      - JAVA_TOOL_OPTIONS=-Dreactor.schedulers.defaultAutomaticContextPropagation=true
    networks:
      - app-network

  connection-service:
    image: rahulranjan26/linkedin-app-connection-service:latest
    container_name: connection-service
    environment:
      - EUREKA_CLIENT_SERVICEURL_DEFAULTZONE=http://discovery-service:8761/eureka
      - SPRING_KAFKA_BOOTSTRAP_SERVERS=kafka:9092
      - SPRING_NEO4J_URI=bolt://connection-db:7687
      - SPRING_NEO4J_AUTHENTICATION_USERNAME=neo4j
      - SPRING_NEO4J_AUTHENTICATION_PASSWORD=password
      - spring.kafka.bootstrap-servers=kafka:9092
      - spring.kafka.consumer.bootstrap-servers=kafka:9092
      - KAFKA_BOOTSTRAP_SERVERS=kafka:9092
      - ZIPKIN_URL=http://zipkin:9411
    depends_on:
      kafka:
        condition: service_healthy
      discovery-service:
        condition: service_started
      connection-db:
        condition: service_started
      zipkin:
        condition: service_started
    networks:
      - app-network

  connection-db:
    image: neo4j:latest
    container_name: connection-db
    environment:
      NEO4J_AUTH: neo4j/password
    ports:
      - "7474:7474"
      - "7687:7687"
    volumes:
      - neo4j-data:/data
    networks:
      - app-network

  notification-service:
    image: rahulranjan26/linkedin-app-notification-service:latest
    container_name: notification-service
    depends_on:
      notification-db:
        condition: service_healthy
      kafka:
        condition: service_healthy
      discovery-service:
        condition: service_started
      zipkin:
        condition: service_started
    environment:
      - SPRING_DATASOURCE_URL=jdbc:postgresql://notification-db:5432/notification
      - SPRING_DATASOURCE_USERNAME=postgres
      - SPRING_DATASOURCE_PASSWORD=rahul@1995
      - SPRING_KAFKA_BOOTSTRAP_SERVERS=kafka:9092
      - EUREKA_CLIENT_SERVICEURL_DEFAULTZONE=http://discovery-service:8761/eureka
      - ZIPKIN_URL=http://zipkin:9411
    networks:
      - app-network

  notification-db:
    image: postgres:16
    container_name: notification-db
    environment:
      POSTGRES_DB: notification
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: rahul@1995
    ports:
      - "5434:5432"
    volumes:
      - notification-db-data:/var/lib/postgresql/data
    healthcheck:
      test: [ "CMD-SHELL", "pg_isready -U postgres -d notification" ]
      interval: 5s
      timeout: 5s
      retries: 5
    networks:
      - app-network

  uploader-service:
    image: rahulranjan26/linkedin-app-uploader-service:latest
    container_name: uploader-service
    depends_on:
      - discovery-service
      - zipkin
    ports:
      - "9050:9050"
    environment:
      - EUREKA_CLIENT_SERVICEURL_DEFAULTZONE=http://discovery-service:8761/eureka
      - CLOUDINARY_CLOUD_NAME=dnvovkm1j
      - CLOUDINARY_API_KEY=213896843617131
      - CLOUDINARY_API_SECRET=4ecv2dFQDe-XTGrfWR1po5nh0sA
      - ZIPKIN_URL=http://zipkin:9411
    networks:
      - app-network

  post-service:
    image: rahulranjan26/linkedin-app-post-service:latest
    container_name: post-service
    depends_on:
      post-db:
        condition: service_healthy
      kafka:
        condition: service_healthy
      discovery-service:
        condition: service_started
      zipkin:
        condition: service_started
    environment:
      - SPRING_DATASOURCE_URL=jdbc:postgresql://post-db:5432/postservice
      - SPRING_DATASOURCE_USERNAME=postgres
      - SPRING_DATASOURCE_PASSWORD=rahul@1995
      - SPRING_KAFKA_BOOTSTRAP_SERVERS=kafka:9092
      - EUREKA_CLIENT_SERVICEURL_DEFAULTZONE=http://discovery-service:8761/eureka
      - ZIPKIN_URL=http://zipkin:9411
    networks:
      - app-network

  post-db:
    image: postgres:16
    container_name: post-db
    environment:
      POSTGRES_DB: postservice
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: rahul@1995
    ports:
      - "5433:5432"
    volumes:
      - post-db-data:/var/lib/postgresql/data
    healthcheck:
      test: [ "CMD-SHELL", "pg_isready -U postgres -d postservice" ]
      interval: 5s
      timeout: 5s
      retries: 5
    networks:
      - app-network

  user-service:
    image: rahulranjan26/linkedin-app-user-service:latest
    container_name: user-service
    depends_on:
      user-db:
        condition: service_healthy
      kafka:
        condition: service_healthy
      discovery-service:
        condition: service_started
      zipkin:
        condition: service_started
    environment:
      - SPRING_DATASOURCE_URL=jdbc:postgresql://user-db:5432/userservice
      - SPRING_DATASOURCE_USERNAME=postgres
      - SPRING_DATASOURCE_PASSWORD=rahul@1995
      - SPRING_SECRET_KEY=dskjjnkfasndifuqhwkndsljfqadskmnadsjfiqjfkanKJkskanskniasmvjabasnanvksdnksaknkbajhvbvasbvakbvakslaabs
      - EUREKA_CLIENT_SERVICEURL_DEFAULTZONE=http://discovery-service:8761/eureka
      - SPRING_KAFKA_BOOTSTRAP_SERVERS=kafka:9092
      - ZIPKIN_URL=http://zipkin:9411
    networks:
      - app-network

  user-db:
    image: postgres:16
    container_name: user-db
    environment:
      POSTGRES_DB: userservice
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: rahul@1995
    ports:
      - "5435:5432"
    volumes:
      - user-db-data:/var/lib/postgresql/data
    healthcheck:
      test: [ "CMD-SHELL", "pg_isready -U postgres -d userservice" ]
      interval: 5s
      timeout: 5s
      retries: 5
    networks:
      - app-network

  kafka:
    image: confluentinc/cp-kafka:7.7.0
    container_name: kafka
    ports:
      - "9092:9092"
      - "29092:29092"
    environment:
      KAFKA_NODE_ID: 1
      KAFKA_PROCESS_ROLES: broker,controller
      KAFKA_LISTENERS: PLAINTEXT://0.0.0.0:9092,CONTROLLER://0.0.0.0:9093,EXTERNAL://0.0.0.0:29092
      KAFKA_ADVERTISED_LISTENERS: PLAINTEXT://kafka:9092,EXTERNAL://localhost:29092
      KAFKA_CONTROLLER_LISTENER_NAMES: CONTROLLER
      KAFKA_LISTENER_SECURITY_PROTOCOL_MAP: CONTROLLER:PLAINTEXT,PLAINTEXT:PLAINTEXT,EXTERNAL:PLAINTEXT
      KAFKA_CONTROLLER_QUORUM_VOTERS: 1@kafka:9093
      KAFKA_OFFSETS_TOPIC_REPLICATION_FACTOR: 1
      KAFKA_TRANSACTION_STATE_LOG_REPLICATION_FACTOR: 1
      KAFKA_TRANSACTION_STATE_LOG_MIN_ISR: 1
      KAFKA_LOG_DIRS: /var/lib/kafka/data
      CLUSTER_ID: MkU3OEVBNTcwNTJENDM2Qk
    volumes:
      - kafka-data:/var/lib/kafka/data
    healthcheck:
      test: [ "CMD", "kafka-topics", "--bootstrap-server", "localhost:9092", "--list" ]
      interval: 10s
      timeout: 10s
      retries: 20
      start_period: 30s
    networks:
      - app-network

  kafdrop:
    image: obsidiandynamics/kafdrop:latest
    container_name: kafdrop
    ports:
      - "9000:9000"
    environment:
      KAFKA_BROKERCONNECT: kafka:9092
    depends_on:
      kafka:
        condition: service_healthy
    networks:
      - app-network

volumes:
  notification-db-data:
  post-db-data:
  user-db-data:
  neo4j-data:
  kafka-data:

networks:
  app-network:
    driver: bridge