spring:
  application:
    name: uploader-service

  servlet:
    multipart:
      max-file-size: 10MB
      max-request-size: 50MB

management:
  tracing:
    sampling:
      probability: 1.0  # 1.0 captures 100% of requests
  zipkin:
    tracing:
      endpoint: "${ZIPKIN_URL:http://localhost:9411}/api/v2/spans"
  endpoints:
    web:
      exposure:
        include: "*"




server:
  port: 9050
  servlet:
    context-path: /api/v1/upload

eureka:
  client:
    service-url:
      defaultZone: ${EUREKA_CLIENT_SERVICEURL_DEFAULTZONE:http://localhost:8761/eureka}
    register-with-eureka: true
    fetch-registry: true

cloudinary:
  cloud-name: ${CLOUDINARY_CLOUD_NAME:dnvovkm1j}
  api-key: ${CLOUDINARY_API_KEY:213896843617131}
  api-secret: ${CLOUDINARY_API_SECRET:4ecv2dFQDe-XTGrfWR1po5nh0sA}


logging:
  pattern:
    level: "%5p [${spring.application.name:},%X{traceId:-},%X{spanId:-}]"